server:
  port: 8443
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 11MB

  freemarker:
    suffix: .ftl

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token:
  signing:
    key: ${JWT_KEY}

dropbox:
  access:
    token: ${DROPBOX_TOKEN}
    refresh-token: ${DROPBOX_REFRESH_TOKEN}
    url: https://api.dropboxapi.com/oauth2/token
    uid: ${DROPBOX_UID}
    account-id: ${DROPBOX_ACCOUNT_ID}
  app:
    key: ${DROPBOX_APP_KEY}
    secret: ${DROPBOX_APP_SECRET}

logging:
  level:
    org.springframework.web: trace

google:
  places:
    api:
      key: ${GOOGLE_PLACES_KEY}

aws:
  s3:
    bucket: ${AWS_BUCKET}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: eu-north-1